services:
  proxyscotch:
    image: ssqlone/proxyscotch:latest
    container_name: proxyscotch
    networks:
      - hoppscotch_default
    expose:
      - 9159
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://127.0.0.1:9159'
      interval: 60s
      timeout: 20s
      retries: 5
networks:
  hoppscotch_default:
    external: true
